### ISSUE TITLE
Add circuit diagram

### ISSUE THREAD

**Issue by ukhov79** [okalachev/flix#3]
I made an circuit diagram for assembly, but with a different receiver.
Maybe add it for those who want to build a quadcopter?
I will test it completely no earlier than mid-January. I'm waiting for parts from Aliexpress...
![Flix Circuit Diagram for R6DSM](https://github.com/okalachev/flix/assets/38152650/5f6a31e6-6aee-4aa6-ba9a-33333ded0243)

**Comment by okalachev** [comment]
Hi, I would like to keep the visual style of all the diagrams consistent (as I'm thinking of making something like a textbook, article, or whatever).

But, since for now, there is absolutely no complete circuit diagram for the project, I added a link to your version to the readme as a user-contributed schematics.

**Comment by okalachev** [comment]
There is an issue in this diagram: RC receiver should be connected to `u2RXD` (UART 2), not to `RXD` (UART 0).

**Comment by ukhov79** [comment]
Thanks! I have adjusted the diagram.
I will make adjustments as I build. [Link to diagram in Miro](https://miro.com/app/board/uXjVN-dTjoo=/?share_link_id=904928044157).
![Flix Circuit Diagram for R6DSM](https://github.com/okalachev/flix/assets/38152650/002f4851-b648-4a82-8ba3-161d15fef869)

**Comment by ukhov79** [comment]
Final version with esp32 power issues.
![Flix Circuit Diagram for R6DSM - Flix Circuit Diagram for R6DSM receiver](https://github.com/okalachev/flix/assets/38152650/1b3f10dc-c020-45d8-8aea-ebf50d45ed12)
